name: food_mobile_app
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1

  line_icons: ^2.0.1
  custom_navigation_bar: ^0.8.2
  google_fonts: ^2.3.1
  animate_do: ^2.1.0
  lottie: ^1.2.2
  flutter_spinkit: ^5.1.0
  concentric_transition: ^1.0.1+1
  get_storage: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true
  assets:
   - assets/images/


